### ISSUE TITLE
顶层项目文件（`Top.scala`）位置？

### ISSUE THREAD

**Issue by yuxuan-z19** [adamgallas/FireFly-v2#1]
您好，想请 顶层项目文件（类似于`Top.scala`，会导出一个基于SystemVerilog的SoC设计）的位置？
> 方便的话可否在README中说明？万分感激！

我注意到每个component有自己的`main()`，是否需要先导出SystemVerilog后手动组织？

**Comment by adamgallas** [comment]
不好意思，我属实比较懒，readme可能得看心情什么时候有空再写了。top module在src/FireFlyv2_2/source/AXIFireFlyFaster.scala这里，整体仿真的module在src/FireFlyv2_2/sim/SimFireFlyFasterMultiTask.scala这里。

**Comment by yuxuan-z19** [comment]
收到，感谢！
