### ISSUE TITLE
Will the bitstrem and the pynq driver be updated?

### ISSUE THREAD

**Issue by ColsonZhang** [adamgallas/FireFly-v2#5]
Will the bitstrem and the pynq driver be updated just like FireFly-v1?
It will be nice for learning the whole project.
Looking forward to it.

**Comment by adamgallas** [comment]
This project hasn’t gone through on-board verification yet. It passes simulation, implementation, and meets timing closure, but I just don't have the energy to go through the on-board debugging process again like I did with FireFly-v1. I also don’t have the time to create a full tutorial or README for this repo at the moment. But I am confident that the repo has all the code you need to build the hardware.

If you need any further support, feel free to open an issue anytime or reach out via email. I'll do my best to help!

**Comment by ColsonZhang** [comment]
Understand. The pynq driver is indeed very annoying!
Thank you very much any way!
